### ISSUE TITLE
WriteMPS vs WriteLP

### ISSUE THREAD

**Issue by aabbas90** [MaxiBoether/mis-benchmark-framework#7]
Hi, Thanks for the extensive study!

I just observed that there is some issue in exporting to .mps format at the following location. Specifically the generated ILP is already tight at the LP root relaxation with `0` objective value:

https://github.com/MaxiBoether/mis-benchmark-framework/blob/66211bb8aecf4f100dc8feebbaf78216e0e03037/solvers/gurobi/main.py#L50

When I change it to `writeLP` instead then it is not the case and the LP relaxations are not tight. I tried on SATLIB and ER graphs.

**Comment by MaxiBoether** [comment]
Hi Ahmad,

Thank you very much for your comment! Please bear with me, it has been quite a while since working on this. If I remember correctly, we used the mps file to run grbtune. 

I am certainly no expert in how to best use Gurobi's API. Mainly we followed the Gurobi user guide [1] which states both MPS and LP files can be used. Consulting [2], it seems to me like MPS files are more "precise" than LP files, which probably why we defaulted to them at the time.

Do I understand correctly that the mps file generated by pulp is not _correct_, compared to the LP file? If so, do you think this is a bug in our usage/framework or within PuLP?

Thank you so much for your help.

[1] https://www.gurobi.com/documentation/9.5/refman/command_line_tuning.html 
[2] https://support.gurobi.com/hc/en-us/articles/360013420131-What-are-the-differences-between-LP-and-MPS-file-formats-

**Comment by aabbas90** [comment]
Ok looks like issue is because when gurobi reads those `.mps` files it is minimizing the objective instead of maximizing. I guess issue is in pulp or mps format in general. 
Reference and solution: https://support.gurobi.com/hc/en-us/articles/360013420371-Why-does-my-MPS-file-produce-different-objectives-with-different-solvers-

Looks like an existing issue with pulp:
https://github.com/coin-or/pulp/issues/459

Overall I think a potential user of this benchmark can have a pitfall if he/she exports the instances as `.mps` and then uses gurobi to solve them. For me atleast, the problem is resolved :)
